Feature/footer
funz1k/teamproject_project14 pull request #1
Opened 2022-01-15 11:15 UTC by NataliiaHrynchuk

Набран HTML, в папку images добавлен файл icon_footer.svg, изменен цвет фона секции

2022-01-15 14:29 UTC, funz1k requested changes

2022-01-15 14:29 UTC, funz1k commented on src/partials/footer.html
> +    <p class="footer">homemade ice cream made</p>
Добавить сервисный класс container который оборачивает весь контент секции

2022-01-15 14:29 UTC, funz1k commented on src/partials/footer.html
> +<footer>
Обычно делают футер класс footer

2022-01-15 14:29 UTC, funz1k commented on src/partials/footer.html
> +    <p class="footer">homemade ice cream made</p>
Изменить класс например на footer__subtitle

2022-01-15 14:29 UTC, funz1k commented on src/partials/footer.html
> +    <p>Feel free to contact</p>
Думаю лучше обернуть текст и контакты в один блок с классом например footer__contacts

2022-01-15 14:29 UTC, funz1k commented on src/partials/footer.html
> +    <div class="footer__copyright">© 2022 - IceCream. All Rights Reserved.</div>
Тега p будет достаточно здесь не нужен div. Пример для создания копирайта https://www.html.am/html-codes/character-codes/html-copyright-code.cfm

2022-01-16 22:13 UTC, NataliiaHrynchuk commented on src/partials/footer.html
> +    <p class="footer">homemade ice cream made</p>
добавила

2022-01-16 22:14 UTC, NataliiaHrynchuk commented on src/partials/footer.html
> +<footer>
done

2022-01-16 22:14 UTC, NataliiaHrynchuk commented on src/partials/footer.html
> +    <p class="footer">homemade ice cream made</p>
done

2022-01-16 22:15 UTC, NataliiaHrynchuk commented on src/partials/footer.html
> +    <div class="footer__copyright">© 2022 - IceCream. All Rights Reserved.</div>
done

2022-01-16 22:30 UTC, closed without merging