add slider
funz1k/teamproject_project14 pull request #6
Opened 2022-01-16 21:22 UTC by fatrathat

Добавил слайдер:
- переопределил контейнер под размеры экрана;
- загрузил изображения под ретину и обычные;
- загрузил иконку дома на маркеры;
- линия под текстом выполнена градиентом;
- добавил псевдоэлемент "кавычки";

2022-01-17 07:59 UTC, funz1k requested changes

2022-01-17 07:59 UTC, funz1k commented on src/sass/components/_reviews.scss
> +    position: absolute;
Спозиционировать кавычки налазят на текст

2022-01-17 12:43 UTC, fatrathat commented on src/sass/components/_reviews.scss
> +    position: absolute;
Готово

2022-01-18 06:58 UTC, funz1k approved these changes

2022-01-18 06:58 UTC, merged