Feature/footer
funz1k/teamproject_project14 pull request #7
Opened 2022-01-17 05:31 UTC by NataliiaHrynchuk

2022-01-17 07:54 UTC, funz1k requested changes
Доработайте и скиньте заново на проверку.

2022-01-17 07:54 UTC, funz1k commented on src/partials/footer.html
> +    <div class="footer__section">
Вместо div используется тег section

2022-01-17 07:54 UTC, funz1k commented on src/sass/components/_footer.scss
> +.footer__wrap {
Нужно сделать флексом с вот такими настройками c 320 по 1280    
display: flex;
flex-direction: column;
align-content: center;
text-align: left;

2022-01-17 07:54 UTC, funz1k commented on src/sass/components/_footer.scss
> +  margin-top: 45px;
Пробивающий маржин. Его переносим на родителя на footer__hookup

2022-01-17 07:54 UTC, funz1k commented on src/sass/components/_footer.scss
> +  height: 76px;
Не нужна высота

2022-01-17 16:38 UTC, NataliiaHrynchuk commented on src/partials/footer.html
> +    <div class="footer__section">
Якщо ставити section, то валідатор свариться, що в секції має бути заголовок, а в футері не має бути заголовків.

2022-01-17 17:51 UTC, NataliiaHrynchuk commented on src/sass/components/_footer.scss
> +.footer__wrap {
done

2022-01-17 17:52 UTC, NataliiaHrynchuk commented on src/sass/components/_footer.scss
> +  margin-top: 45px;
done

2022-01-17 17:52 UTC, NataliiaHrynchuk commented on src/sass/components/_footer.scss
> +  height: 76px;
done

2022-01-18 11:16 UTC, funz1k approved these changes

2022-01-18 11:16 UTC, funz1k commented on src/sass/components/_footer.scss
> +  @media screen and (min-width: 480px) {
При 480 этот контейнер переписывает контейнер из сервиса. Необходимо убрать

2022-01-18 11:16 UTC, merged